# Generated by Django 5.1.2 on 2024-12-07 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('background_id', models.AutoField(primary_key=True, serialize=False)),
                ('backgroundName', models.CharField(max_length=25)),
                ('abilitiesImprovedOne', models.CharField(max_length=3)),
                ('abilitiesImprovedTwo', models.CharField(max_length=3)),
                ('abilitiesImprovedThree', models.CharField(max_length=3)),
                ('descript', models.TextField()),
            ],
            options={
                'db_table': 'Background',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('className', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descript', models.TextField()),
                ('hitDice', models.CharField(max_length=4)),
                ('savingThrowOne', models.CharField(max_length=3)),
                ('savingThrowTwo', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('feat_id', models.AutoField(primary_key=True, serialize=False)),
                ('featName', models.CharField(max_length=50)),
                ('descript', models.TextField()),
                ('lvlReq', models.IntegerField()),
            ],
            options={
                'db_table': 'Feat',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.AutoField(primary_key=True, serialize=False)),
                ('race_name', models.CharField(max_length=20)),
                ('descript', models.TextField()),
                ('speed', models.IntegerField()),
                ('size', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Race',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('spell_id', models.AutoField(primary_key=True, serialize=False)),
                ('SpellName', models.CharField(max_length=30)),
                ('spellLvl', models.IntegerField()),
                ('descript', models.TextField(db_column='description')),
                ('school', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Spell',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='WpnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpnTypeName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'WpnType',
            },
        ),
        migrations.CreateModel(
            name='Character_Class',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=255)),
                ('STR', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('INTE', models.IntegerField()),
                ('WIS', models.IntegerField()),
                ('CHA', models.IntegerField()),
                ('background', models.ForeignKey(db_column='background', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnd_app.background')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnd_app.race')),
            ],
            options={
                'db_table': 'Character_Class',
            },
        ),
        migrations.CreateModel(
            name='ClassByLvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField()),
                ('Ability', models.TextField(default='Feat')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.classes')),
            ],
            options={
                'db_table': 'ClassByLvl',
            },
        ),
        migrations.CreateModel(
            name='CharacterByLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField()),
                ('abilityName', models.CharField(max_length=50)),
                ('lvl', models.IntegerField()),
                ('lvl1stSpellSlot', models.IntegerField(blank=True, null=True)),
                ('lvl2ndSpellSlot', models.IntegerField(blank=True, null=True)),
                ('lvl3rdSpellSlot', models.IntegerField(blank=True, null=True)),
                ('lvl4thSpellSlot', models.IntegerField(blank=True, null=True)),
                ('lvl5thSpellSlot', models.IntegerField(blank=True, null=True)),
                ('lvl6thSpellSlot', models.IntegerField(blank=True, null=True)),
                ('lvl7thSpellSlot', models.IntegerField(blank=True, null=True)),
                ('lvl8thSpellSlot', models.IntegerField(blank=True, null=True)),
                ('lvl9thSpellSlot', models.IntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.character_class')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.classes')),
            ],
            options={
                'db_table': 'CharacterByLevel',
            },
        ),
        migrations.CreateModel(
            name='CharacterByFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.character_class')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.feat')),
            ],
            options={
                'db_table': 'CharacterByFeat',
            },
        ),
        migrations.AddField(
            model_name='background',
            name='feat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.feat'),
        ),
        migrations.CreateModel(
            name='AbilityByRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvlGainedAt', models.IntegerField(default=1)),
                ('ability', models.TextField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.race')),
            ],
            options={
                'db_table': 'AbilityByRace',
            },
        ),
        migrations.CreateModel(
            name='SkillsbyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.classes')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.skill')),
            ],
            options={
                'db_table': 'SkillsbyClass',
            },
        ),
        migrations.CreateModel(
            name='CurrentSpellsForCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.character_class')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.spell')),
            ],
            options={
                'db_table': 'CurrentSpellsForCharacter',
            },
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('subclass_id', models.AutoField(primary_key=True, serialize=False)),
                ('subclass_name', models.CharField(max_length=30)),
                ('descript', models.TextField()),
                ('className', models.ForeignKey(db_column='className', on_delete=django.db.models.deletion.CASCADE, to='dnd_app.classes')),
            ],
            options={
                'db_table': 'Subclass',
            },
        ),
        migrations.CreateModel(
            name='SubclassByLvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField()),
                ('descript', models.TextField()),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.subclass')),
            ],
            options={
                'db_table': 'SubclassByLvl',
            },
        ),
        migrations.CreateModel(
            name='ToolByClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.classes')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.tool')),
            ],
            options={
                'db_table': 'ToolbyClass',
            },
        ),
        migrations.CreateModel(
            name='WhoCanCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.classes')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.spell')),
            ],
            options={
                'db_table': 'whoCanCast',
            },
        ),
        migrations.CreateModel(
            name='WpnTypeByClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.classes')),
                ('wpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.wpntype')),
            ],
            options={
                'db_table': 'wpnTypebyClass',
            },
        ),
    ]
