# Generated by Django 5.1.2 on 2024-11-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classes',
            table='Classes',
        ),
    ]
