# Generated by Django 5.1.2 on 2024-12-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterByClassAndSubclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.character_class')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.classes')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.subclass')),
            ],
        ),
    ]
