# Generated by Django 5.1.2 on 2024-12-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0002_characterbyclassandsubclass'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='characterbyclassandsubclass',
            table='CharacterByClassAndSubclass',
        ),
    ]
