# Generated by Django 5.1.2 on 2024-11-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0002_alter_classes_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feat',
            name='id',
        ),
        migrations.AddField(
            model_name='feat',
            name='feat_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
