# Generated by Django 5.1.2 on 2024-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0003_remove_feat_id_feat_feat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='id',
        ),
        migrations.AddField(
            model_name='spell',
            name='feat_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.CharField(default='noSchool', max_length=1000),
            preserve_default=False,
        ),
    ]
