# Generated by Django 5.1.2 on 2024-12-07 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0003_alter_characterbyclassandsubclass_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterbyclassandsubclass',
            name='character_class',
            field=models.ForeignKey(db_column='className', on_delete=django.db.models.deletion.CASCADE, to='dnd_app.classes'),
        ),
    ]
