# Generated by Django 5.1.2 on 2024-12-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0004_alter_characterbyclassandsubclass_character_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitybyrace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
