# Generated by Django 5.1.2 on 2024-11-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0004_remove_spell_id_spell_feat_id_spell_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='feat_id',
            new_name='spell_id',
        ),
    ]
