# Generated by Django 5.1.2 on 2024-11-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0005_rename_feat_id_spell_spell_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='id',
        ),
        migrations.AddField(
            model_name='race',
            name='race_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='descript',
            field=models.TextField(db_column='description'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='descript',
            field=models.TextField(db_column='description'),
        ),
    ]
