# Generated by Django 5.1.2 on 2024-11-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0007_alter_race_descript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='id',
        ),
        migrations.AddField(
            model_name='background',
            name='background_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
